# Use a base image with Python
FROM python:3.11-slim

# Install system dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    gcc \
    libc-dev \
    python3-venv \
    rustc \
    cargo \
    && rm -rf /var/lib/apt/lists/*

# Set the working directory inside the container
WORKDIR /app

# Install poetry
RUN python3 -m pip install --upgrade pip && pip install poetry

# Copy the pyproject.toml and poetry.lock files into the container
COPY pyproject.toml poetry.lock ./

# Install dependencies using poetry
RUN poetry config virtualenvs.create false && poetry install --no-dev

# Copy the rest of the application code into the container
COPY . .

# Command to run the bot
CMD ["python", "main.py"]
